#![allow(unused_imports, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod context;
pub mod ierc20;
pub mod erc20;
pub mod erc20logger;
pub mod exampletoken;
pub mod ierc165;
pub mod ierc20metadata;
pub mod ierc721;
pub mod ierc721enumerable;
pub mod ierc721metadata;
pub mod ierc721tokenreceiver;
pub mod mockerc20;
pub mod mockerc721;
pub mod ierc1155errors;
pub mod ierc20errors;
pub mod ierc721errors;
